
/****************************/
/** SCRIPT MODELO DE DATOS **/
/**    ODS_ESTADISTICAS               */
/***************************/


CREATE TABLE [dbo].[I_MAPEO_CONTINGENCIA](
	[operation_date] [date] NULL,
	[local_date] [date] NULL,
	[flight_number] [int] NULL,
	[boardpoint] [varchar](3) NULL,
	[offpoint] [varchar](3) NULL,
	[fecha_vuelo_comercial] [date] NULL,
	[vuelo_comercial] [int] NULL,
	[origen_comercial] [varchar](3) NULL,
	[destino_comercial] [varchar](3) NULL,
	[pax_light] [int] NULL,
	[pax_plus] [int] NULL,
	[pax_no_pago] [int] NULL,
	[pax_pago] [int] NULL,
	[pax_total] [int] NULL,
	[capacity] [int] NULL,
	[travel_distance] [int] NULL,
	[ask] [int] NULL,
	[rpk_light] [int] NULL,
	[rpk_plus] [int] NULL,
	[rpk_no_pago] [int] NULL,
	[rpk_pago] [int] NULL,
	[rpk_total] [int] NULL,
	[agrupacion] [varchar](10) NULL,
	[routing] [varchar](25) NULL,
	[routing_eerr] [varchar](25) NULL,
	[ruta] [varchar](10) NULL,
	[subruta] [varchar](10) NULL,
	[mapear] [varchar](2) NULL
) ON [PRIMARY]
GO

;

CREATE TABLE [dbo].[I_VALIDACION](
	[fecha_local] [date] NULL,
	[fecha_utc] [date] NULL,
	[mes] [int] NULL,
	[año] [int] NULL,
	[numero_vuelo] [int] NULL,
	[ciudad_partida] [varchar](3) NULL,
	[ciudad_arribo] [varchar](3) NULL,
	[tramo] [varchar](6) NULL,
	[leg] [int] NULL,
	[material] [int] NULL,
	[matricula] [varchar](3) NULL,
	[status_vuelo] [varchar](3) NULL,
	[tipo_vuelo] [varchar](8) NULL,
	[block_time] [time](0) NULL,
	[air_time] [time](0) NULL,
	[block_time_dec] [float] NULL,
	[air_time_dec] [float] NULL,
	[distancia] [int] NULL,
	[bkgs] [int] NULL,
	[bkgs_pago] [int] NULL,
	[ask] [int] NULL,
	[rpk] [int] NULL,
	[rpk_pago] [int] NULL,
	[hora_partida_itinerario] [time](0) NULL,
	[hora_llegada_itinerario] [time](0) NULL,
	[off_block] [time](0) NULL,
	[on_block] [time](0) NULL,
	[take_off] [time](0) NULL,
	[touch_down] [time](0) NULL,
	[routing] [varchar](25) NULL,
	[agrupacion] [varchar](10) NULL,
	[ruta] [varchar](10) NULL,
	[subruta] [varchar](10) NULL,
	[al_partir] [int] NULL,
	[al_partir_lts] [float] NULL,
	[remanente] [int] NULL,
	[remanente_lts] [float] NULL,
	[consumo_klg] [int] NULL,
	[consumo_lts] [float] NULL,
	[carguio_lts] [int] NULL,
	[take_of_weight] [int] NULL,
	[apu_kg] [float] NULL,
	[apu_lts] [float] NULL,
	[especial] [int] NOT NULL,
	[capacidad] [int] NULL,
	[tipo_cruce] [varchar](6) NOT NULL
) ON [PRIMARY]
GO

;

CREATE TABLE [dbo].[O_ESTADISTICA](
	[local_date] [date] NULL,
	[utc_date] [date] NULL,
	[año] [int] NULL,
	[mes] [int] NULL,
	[flight_number] [int] NULL,
	[boardpoint] [varchar](3) NULL,
	[offpoint] [varchar](3) NULL,
	[di_leg] [varchar](6) NULL,
	[nd_leg] [varchar](6) NULL,
	[leg_number] [int] NULL,
	[flight_type] [varchar](25) NULL,
	[pax_light] [int] NULL,
	[pax_plus] [int] NULL,
	[pax_no_pago] [int] NULL,
	[pax_pago] [int] NULL,
	[pax_total] [int] NULL,
	[capacity] [int] NULL,
	[travel_distance] [int] NULL,
	[ask] [int] NULL,
	[rpk_light] [int] NULL,
	[rpk_plus] [int] NULL,
	[rpk_no_pago] [int] NULL,
	[rpk_pago] [int] NULL,
	[rpk_total] [int] NULL,
	[agrupacion] [varchar](10) NULL,
	[routing] [varchar](25) NULL,
	[routing_eerr] [varchar](25) NULL,
	[ruta] [varchar](10) NULL,
	[subruta] [varchar](10) NULL,
	[aircraft_type] [varchar](10) NULL,
	[ac] [varchar](3) NULL,
	[status] [varchar](3) NULL,
	[std] [smalldatetime] NULL,
	[sta] [smalldatetime] NULL,
	[atd] [smalldatetime] NULL,
	[ata] [smalldatetime] NULL,
	[block_time] [time](0) NULL,
	[block_time_dec] [float] NULL,
	[take_off] [smalldatetime] NULL,
	[touch_down] [smalldatetime] NULL,
	[air_time] [time](0) NULL,
	[air_time_dec] [float] NULL,
	[block_off_fuel] [float] NULL,
	[block_on_fuel] [float] NULL,
	[burn_fuel] [float] NULL,
	[fuel_uplift] [float] NULL,
	[apu_burn_fuel] [float] NULL,
	[original_flight_number] [int] NULL,
	[original_departure_date] [date] NULL,
	[original_boardpoint] [varchar](3) NULL,
	[original_offpoint] [varchar](3) NULL,
	[tipo_cruce] [varchar](25) NULL
) ON [PRIMARY]
GO

;

CREATE TABLE [dbo].[T_PRE_ESTADISTICA](
	[local_date] [date] NULL,
	[utc_date] [date] NULL,
	[año] [int] NULL,
	[mes] [int] NULL,
	[flight_number] [int] NULL,
	[boardpoint] [varchar](3) NULL,
	[offpoint] [varchar](3) NULL,
	[di_leg] [varchar](6) NULL,
	[nd_leg] [varchar](6) NULL,
	[leg_number] [int] NULL,
	[flight_type] [varchar](25) NULL,
	[pax_light] [int] NULL,
	[pax_plus] [int] NULL,
	[pax_no_pago] [int] NULL,
	[pax_pago] [int] NULL,
	[pax_total] [int] NULL,
	[capacity] [int] NULL,
	[travel_distance] [int] NULL,
	[ask] [int] NULL,
	[rpk_light] [int] NULL,
	[rpk_plus] [int] NULL,
	[rpk_no_pago] [int] NULL,
	[rpk_pago] [int] NULL,
	[rpk_total] [int] NULL,
	[agrupacion] [varchar](10) NULL,
	[routing] [varchar](25) NULL,
	[routing_eerr] [varchar](25) NULL,
	[ruta] [varchar](10) NULL,
	[subruta] [varchar](10) NULL,
	[aircraft_type] [varchar](10) NULL,
	[ac] [varchar](3) NULL,
	[status] [varchar](3) NULL,
	[std] [smalldatetime] NULL,
	[sta] [smalldatetime] NULL,
	[atd] [smalldatetime] NULL,
	[ata] [smalldatetime] NULL,
	[block_time] [time](0) NULL,
	[block_time_dec] [float] NULL,
	[take_off] [smalldatetime] NULL,
	[touch_down] [smalldatetime] NULL,
	[air_time] [time](0) NULL,
	[air_time_dec] [float] NULL,
	[block_off_fuel] [float] NULL,
	[block_on_fuel] [float] NULL,
	[burn_fuel] [float] NULL,
	[fuel_uplift] [float] NULL,
	[apu_burn_fuel] [float] NULL,
	[original_flight_number] [int] NULL,
	[original_departure_date] [date] NULL,
	[original_boardpoint] [varchar](3) NULL,
	[original_offpoint] [varchar](3) NULL,
	[tipo_cruce] [varchar](25) NULL
) ON [PRIMARY]
GO

;

CREATE TABLE [dbo].[T_RESUMEN_PAX](
	[flight_number] [int] NULL,
	[boardpoint] [varchar](3) NULL,
	[offpoint] [varchar](3) NULL,
	[di_leg] [varchar](6) NULL,
	[nd_leg] [varchar](6) NULL,
	[departure_date] [date] NULL,
	[departure_time] [time](0) NULL,
	[arrival_date] [date] NULL,
	[arrival_time] [time](0) NULL,
	[leg_number] [int] NULL,
	[travel_distance] [int] NULL,
	[aircraft_code] [varchar](10) NULL,
	[lid] [int] NULL,
	[capacity] [int] NULL,
	[pax_light] [int] NULL,
	[pax_plus] [int] NULL,
	[pax_no_pago] [int] NULL,
	[pax_total] [int] NULL,
	[ask] [int] NULL,
	[rpk_light] [int] NULL,
	[rpk_plus] [int] NULL,
	[rpk_no_pago] [int] NULL,
	[rpk_total] [int] NULL,
	[routing] [varchar](25) NULL
) ON [PRIMARY]
GO

