
/****************************/
/** SCRIPT MODELO DE DATOS **/
/**       ODS_DISPO_RMS     */
/****************************/


DROP DATABASE ODS_DISPO_RMS;

CREATE DATABASE ODS_DISPO_RMS;


CREATE TABLE [dbo].[RMS_final](
	[fecha_vista] [date] NULL,
	[Flightline] [varchar](50) NULL,
	[FlightPath] [varchar](50) NULL,
	[Fecha] [date] NULL,
	[Wk] [int] NULL,
	[Dept_Time] [varchar](50) NULL,
	[Total_Cap] [int] NULL,
	[Total_Lid] [int] NULL,
	[Total_Bkgs] [int] NULL,
	[Total_Revenue] [int] NULL,
	[Pickup_1] [int] NULL,
	[Pickup_3] [int] NULL,
	[Pickup_5] [int] NULL,
	[Pickup_7] [int] NULL,
	[Pickup_14] [int] NULL,
	[Pickup_21] [int] NULL,
	[Rev_P1] [int] NULL,
	[Rev_P3] [int] NULL,
	[Rev_P5] [int] NULL,
	[Rev_P7] [int] NULL,
	[Rev_P14] [int] NULL,
	[Rev_P21] [int] NULL,
	[Rule_Name] [varchar](200) NULL,
	[Total_LF_Cap] [real] NULL,
	[Total_LF_Lid] [real] NULL,
	[Fare_LA_con_tasas] [int] NULL,
	[Bkg_X] [int] NULL,
	[Bkg_A] [int] NULL,
	[Bkg_U] [int] NULL,
	[Bkg_G] [int] NULL,
	[Rev_G] [int] NULL,
	[Pickup_1_G] [int] NULL,
	[Lowest_Fare_LA] [int] NULL,
	[Y_SA] [int] NULL,
	[K_SA] [int] NULL,
	[V_SA] [int] NULL,
	[H_SA] [int] NULL,
	[S_SA] [int] NULL,
	[B_SA] [int] NULL,
	[L_SA] [int] NULL,
	[R_SA] [int] NULL,
	[T_SA] [int] NULL,
	[M_SA] [int] NULL,
	[N_SA] [int] NULL,
	[Q_SA] [int] NULL,
	[Z_SA] [int] NULL,
	[X_SA] [int] NULL,
	[A_SA] [int] NULL,
	[U_SA] [int] NULL,
	[Curr_H2_Fare] [int] NULL,
	[Grid_Fare_LA] [int] NULL,
	[JA] [int] NULL,
	[Lowest_JA] [int] NULL,
	[OD] [varchar](50) NULL,
	[Numero_vuelo] [varchar](4) NULL,
	[Dia] [int] NULL,
	[Mes] [int] NULL,
	[Año] [int] NULL,
	[DOW] [int] NULL,
	[Cluster] [varchar](7) NULL,
	[Stops] [int] NOT NULL,
	[Subruta] [nvarchar](20) NULL,
	[Cap_Aux_Y] [int] NULL,
	[AP] [int] NULL,
	[Contador] [int] NOT NULL,
	[Dif_vs_LA] [int] NULL,
	[Dif_vs_JA] [int] NULL,
	[Competitivo] [int] NOT NULL,
	[Descompetitivo] [int] NOT NULL,
	[Neutro] [int] NOT NULL,
	[Dispo_X] [int] NOT NULL,
	[Dispo_A] [int] NOT NULL,
	[Dispo_U] [int] NOT NULL,
	[OD_NO_DIR] [varchar](50) NULL,
	[AGRUPACION] [nvarchar](20) NULL,
	[PAR_O_IMPAR] [varchar](5) NOT NULL,
	[Grupos] [varchar](8) NOT NULL,
	[RANGO_AP] [varchar](5) NOT NULL
) ON [PRIMARY]